# -- Main Menu --
# Voci di menu mostrate nell'header. Ordinate per "weight" (dal più basso al più alto).

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Disclosures"
  pageRef = "disclosures"
  weight = 30

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 50

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
